### ISSUE TITLE
App crashes while scrolling a book

### ISSUE THREAD

**Issue by shuvashish76** [Acclorite/book-story#90]
### Describe the bug
Self-explanatory from the title

### To Reproduce
1. Added a ~24MB epub file from browse
2. Open library & start reading it
3. Scroll down fast

### Expected behavior
Read the book without any crashes

### Device Info (please complete the following information):
 - Device: Lenovo Tab4 8 plus
 - Android Version: 9
 - Version of the app: 1.3.0

### Crash Logs:

```
FATAL EXCEPTION: main
Process: ua.acclorite.book_story, PID: 13023
java.lang.IllegalArgumentException: current must not be NaN
	at androidx.compose.ui.semantics.ProgressBarRangeInfo.<init>(Unknown Source:26)
	at androidx.compose.material3.ProgressIndicatorKt$LinearProgressIndicator$3$1.x(Unknown Source:24)
	at androidx.compose.ui.semantics.CoreSemanticsModifierNode.H0(Unknown Source:2)
	at androidx.compose.ui.node.LayoutNode$collapsedSemantics$1.a(Unknown Source:67)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.d(Unknown Source:113)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.a(Unknown Source:56)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.d(Unknown Source:135)
	at androidx.compose.ui.node.OwnerSnapshotObserver.b(Unknown Source:2)
	at androidx.compose.ui.node.LayoutNode.o(Unknown Source:53)
	at androidx.compose.ui.semantics.SemanticsNodeKt.a(Unknown Source:109)
	at androidx.compose.ui.semantics.SemanticsNode.b(Unknown Source:39)
	at androidx.compose.ui.semantics.SemanticsNode.b(Unknown Source:47)
	at androidx.compose.ui.semantics.SemanticsNode.b(Unknown Source:47)
	at androidx.compose.ui.semantics.SemanticsNode.b(Unknown Source:47)
	at androidx.compose.ui.semantics.SemanticsNode.p(Unknown Source:14)
	at androidx.compose.ui.semantics.SemanticsNode.g(Unknown Source:26)
	at androidx.compose.ui.semantics.SemanticsNode.h(Unknown Source:16)
	at androidx.compose.ui.platform.SemanticsUtils_androidKt.b(Unknown Source:299)
	at androidx.compose.ui.platform.SemanticsUtils_androidKt.b(Unknown Source:316)
	at androidx.compose.ui.platform.SemanticsUtils_androidKt.a(Unknown Source:64)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.o(Unknown Source:11)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.B(Unknown Source:34)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.i(Unknown Source:21)
	at E.d.run(Unknown Source:35)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by Acclorite** [comment]
Seems like issue with calculating progress.. Will see, would help if you send the book, as different files show different behavior
